### PR TITLE
ui: Add favicon.

### PR DESCRIPTION
**Pull request by make-github-pseudonymous-again**

### CODE REVIEW

**Comment by holgerdell** [comment]
Isn't this a bacterium?

**Comment by make-github-pseudonymous-again** [comment]
There is no viral emoji!

**Comment by make-github-pseudonymous-again** [comment]
https://favicon.io/emoji-favicons/

**Comment by holgerdell** [comment]
According to [this article](https://blog.emojipedia.org/spread-of-the-coronavirus-emoji/), the Microbe emoji is the one that is most commonly used. So I accept this icon for now.

**Pull request merged**
